#!/bin/bash
# wd-cpu-apply.sh — write every systemd CPU-affinity setting from the plan in wd-cpu-plan.sh.
#
# Without this the layout lives in several hand-edited places that drift apart. Two ways that
# has already bitten:
#   - a stale resctrl cpus_list left one radiod running in the decoders' L3 partition
#   - wsprdaemon.service kept CPUAffinity=6-11 after WD_CPU_CORES changed, so the decoders
#     never used the cores that had been freed for them, while the box looked correctly configured
#
# Writes DROP-INS, never the unit files themselves, so WD regenerating wsprdaemon.service does not
# discard this. systemd merges CPUAffinity= ADDITIVELY, so each drop-in must reset with an empty
# CPUAffinity= first or you get the UNION of old and new.
#
# Does NOT restart anything: it reports which units need a restart and leaves that to you.
# DRY_RUN=1 shows what would change and writes nothing.
set -u
PLAN_CMD="${WD_CPU_PLAN:-/usr/local/sbin/wd-cpu-plan.sh}"
PIN_SCRIPT="${WD_PIN_SCRIPT:-/usr/local/sbin/radiod-pin-threads.sh}"
DRY="${DRY_RUN:-0}"
declare -a NEEDS_RESTART=()

plan=$("$PLAN_CMD" 2>/dev/null) || { echo "wd-cpu-apply: cannot run $PLAN_CMD"; exit 1; }
eval "$plan"
[ "${WD_PLAN_OK:-no}" = "yes" ] || { echo "wd-cpu-apply: no usable plan: ${WD_PLAN_REASON:-unknown}"; exit 0; }

### write $2 to $1 only if the EFFECTIVE settings differ, and note the unit as needing a restart.
### Comments and blank lines are ignored in the comparison: a reworded comment must not trigger a
### radiod restart, because that resets the block-drop counter and destroys a measurement run.
effective(){ grep -vE '^[[:space:]]*(#|$)' 2>/dev/null || true ; }
write_dropin(){
    local path=$1 content=$2 unit=$3
    if [ -f "$path" ] && [ "$(effective < "$path")" = "$(printf '%s\n' "$content" | effective)" ]; then
        echo "  unchanged: $path"
        return 0
    fi
    if [ "$DRY" = "1" ]; then
        echo "  WOULD WRITE $path:"
        echo "$content" | sed 's/^/      /'
    else
        sudo mkdir -p "$(dirname "$path")"
        echo "$content" | sudo tee "$path" >/dev/null
        echo "  wrote: $path"
    fi
    [ -n "$unit" ] && NEEDS_RESTART+=("$unit")
    return 0
}

echo "wd-cpu-apply: ${WD_TOPO_CORES} cores, ${WD_TOPO_SIBLING_STYLE} SMT, ${WD_CORES_PER_RADIOD} core(s)/radiod"

### 1. one drop-in per radiod instance
for i in $(seq 0 $(( ${WD_RADIOD_INSTANCES:-0} - 1 ))); do
    eval "name=\$WD_RADIOD${i}_NAME; cpus=\$WD_RADIOD${i}_CPUS"
    [ -n "${name:-}" ] || continue
    write_dropin "/etc/systemd/system/radiod@${name}.service.d/cpu-affinity.conf" \
"[Service]
# Generated by wd-cpu-apply.sh from wd-cpu-plan.sh -- do not hand-edit.
# The empty CPUAffinity= reset is REQUIRED; systemd merges this directive additively.
CPUAffinity=
CPUAffinity=$(echo "$cpus" | tr ',' ' ')
ExecStartPost=+${PIN_SCRIPT} %i" \
        "radiod@${name}.service"
done

### 2. wsprdaemon.service, if WD runs as a service here.  This is the setting that actually
###    governs where the decoders run; the /sys/fs/cgroup/wsprdaemon cpuset is not used when
###    WD runs under systemd, and writing to it silently does nothing.
if systemctl cat wsprdaemon.service >/dev/null 2>&1 ; then
    write_dropin "/etc/systemd/system/wsprdaemon.service.d/cpu-affinity.conf" \
"[Service]
# Generated by wd-cpu-apply.sh from wd-cpu-plan.sh -- do not hand-edit.
CPUAffinity=
CPUAffinity=$(echo "${WD_DECODER_CPUS}" | tr ',' ' ')" \
        "wsprdaemon.service"
else
    echo "  wsprdaemon.service not present; skipping (WD is not running as a systemd service here)"
fi

### 3. manager default: everything not explicitly pinned stays off the radiod cores
write_dropin "/etc/systemd/system.conf.d/radiod-cpu-affinity.conf" \
"[Manager]
# Generated by wd-cpu-apply.sh -- keeps OS and system services off the radiod cores.
CPUAffinity=$(echo "${WD_OS_CPUS},${WD_DECODER_CPUS}" | tr ',' ' ')" \
    ""

if [ "$DRY" = "1" ]; then
    echo "  (dry run - nothing written, no daemon-reload)"
else
    sudo systemctl daemon-reload
    echo "  daemon-reload done"
fi

if [ ${#NEEDS_RESTART[@]} -eq 0 ]; then
    echo "wd-cpu-apply: no changes; nothing needs restarting"
else
    printf 'wd-cpu-apply: RESTART REQUIRED for: %s\n' "${NEEDS_RESTART[*]}"
    echo "  (not done automatically -- restarting radiod resets its drop counter)"
fi
exit 0
